Issue 1639 (#1653)
* https://github.com/jackdewinter/pymarkdown/issues/1639
* https://github.com/jackdewinter/pymarkdown/issues/1650
* https://github.com/jackdewinter/pymarkdown/issues/1652

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -108,7 +108,14 @@ jobs:
           pipenv graph
 
       - name: Execute Tests
-        run: pipenv run pytest --junitxml=pytest.xml --cov --cov-branch --cov-report xml:coverage.xml
+        run: |
+          pwd
+          pipenv run python -c "import html; print(html.__file__)"
+          pipenv run python -c "import sys; print(sys.path)"
+          # if ! find . -name "html.py" -o -name "html" -type d | grep -v ".venv" | grep -v "__pycache__" ; then
+          #   echo "not found"
+          # fi
+          pipenv run pytest --junitxml=pytest.xml --cov --cov-branch --cov-report xml:coverage.xml
           
       - name: Archive coverage artifacts
         uses: actions/upload-artifact@v7
@@ -242,7 +249,14 @@ jobs:
           pipenv uninstall pytest-html
 
       - name: Execute Tests
-        run: pipenv run pytest --cov-fail-under=90 --cov --cov-branch --cov-report xml:report/coverage.xml
+        run: |
+          pwd
+          pipenv run python -c "import html; print(html.__file__)"
+          pipenv run python -c "import sys; print(sys.path)"
+          # if ! find . -name "html.py" -o -name "html" -type d | grep -v ".venv" | grep -v "__pycache__" ; then
+          #   echo "not found"
+          # fi
+          pipenv run pytest --cov-fail-under=90 --cov --cov-branch --cov-report xml:report/coverage.xml
 
   packaging:
 
